## PANDAS
- PANDAS IS A FAST , POWERFUL AND EASY TO USE OPEN SOURCE DATA ANALYSIS AND MANUPULATION LIBRARY.
    - SERIES
    - DATA FRAME

In [1]:
import numpy as np
import pandas as pd

## SERIES

In [2]:
data = [10,20,30,40,50]
s1 = pd.Series(data)
s1

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [3]:
type(s1)

pandas.core.series.Series

In [4]:
s1.values

array([10, 20, 30, 40, 50])

In [5]:
s1.index

RangeIndex(start=0, stop=5, step=1)

In [6]:
list(s1.index)

[0, 1, 2, 3, 4]

In [7]:
s1.index = [101,102,103,104,105]
s1

101    10
102    20
103    30
104    40
105    50
dtype: int64

In [8]:
s1.index = ['A','B','C','D','E']
s1

A    10
B    20
C    30
D    40
E    50
dtype: int64

In [9]:
s1.index = range(1005,1010)
s1

1005    10
1006    20
1007    30
1008    40
1009    50
dtype: int64

In [10]:
s1.index = ['A','B','C','D','E']
s1

A    10
B    20
C    30
D    40
E    50
dtype: int64

## ACCESSING DATA IN SERIES

In [12]:
s1[0]

C:\Users\roder\AppData\Local\Temp\ipykernel_15632\643609873.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s1[0]

np.int64(10)

In [13]:
s1['A']

np.int64(10)

In [14]:
s1.iloc[1]                                               #  FOR DEFAULT INDEX ILOC

np.int64(20)

In [15]:
s1.loc['B']                                              #  FOR DEFINED INDEX LOC

np.int64(20)

## ADD, UPDATE AND DELETE OPERATIONS

In [16]:
s1['F'] = 60
s1

A    10
B    20
C    30
D    40
E    50
F    60
dtype: int64

In [17]:
s1['B'] = 75
s1

A    10
B    75
C    30
D    40
E    50
F    60
dtype: int64

In [18]:
s1.drop('E')

A    10
B    75
C    30
D    40
F    60
dtype: int64

In [19]:
s1

A    10
B    75
C    30
D    40
E    50
F    60
dtype: int64

In [20]:
s2=s1.drop('E')
s2

A    10
B    75
C    30
D    40
F    60
dtype: int64

In [21]:
s1.drop('E',inplace= True)
s1

A    10
B    75
C    30
D    40
F    60
dtype: int64

## SLICING

In [22]:
s1[:]

A    10
B    75
C    30
D    40
F    60
dtype: int64

In [23]:
s1[2:4]

C    30
D    40
dtype: int64

In [24]:
s1[::-1]

F    60
D    40
C    30
B    75
A    10
dtype: int64

## CREATING SERIES DATA FROM A DICTIONARY

In [25]:
data = { 'Jaipur'     : 'Rajasthan',
         'Mumbai'     : 'Maharashtra',
         'Kolkata'    : 'West Bengal',
         'Chandigarh' : 'Punjab',
         'Patna'      : 'Bihar',
         'Lucknow'    : 'Uttar Pradesh'}

In [26]:
s2 = pd.Series(data)
s2

Jaipur            Rajasthan
Mumbai          Maharashtra
Kolkata         West Bengal
Chandigarh           Punjab
Patna                 Bihar
Lucknow       Uttar Pradesh
dtype: object

In [27]:
s2.iloc[1]

'Maharashtra'

In [28]:
s2.loc['Mumbai']

'Maharashtra'

In [29]:
s2.index

Index(['Jaipur', 'Mumbai', 'Kolkata', 'Chandigarh', 'Patna', 'Lucknow'], dtype='object')

In [30]:
s2.values

array(['Rajasthan', 'Maharashtra', 'West Bengal', 'Punjab', 'Bihar',
       'Uttar Pradesh'], dtype=object)

In [31]:
s2.name = 'States and Capitals'
s2

Jaipur            Rajasthan
Mumbai          Maharashtra
Kolkata         West Bengal
Chandigarh           Punjab
Patna                 Bihar
Lucknow       Uttar Pradesh
Name: States and Capitals, dtype: object

In [32]:
s2.index.name = 'Capitals'
s2

Capitals
Jaipur            Rajasthan
Mumbai          Maharashtra
Kolkata         West Bengal
Chandigarh           Punjab
Patna                 Bihar
Lucknow       Uttar Pradesh
Name: States and Capitals, dtype: object

In [33]:
s2.loc[['Jaipur','Kolkata']]

Capitals
Jaipur       Rajasthan
Kolkata    West Bengal
Name: States and Capitals, dtype: object

In [34]:
s3 = pd.Series(data=s2, index=['Jaipur','Mumbai','Delhi','Bangaluru','Lucknow'])
s3

Jaipur           Rajasthan
Mumbai         Maharashtra
Delhi                  NaN
Bangaluru              NaN
Lucknow      Uttar Pradesh
Name: States and Capitals, dtype: object

## FUNCTIONS

In [35]:
s3.isnull()

Jaipur       False
Mumbai       False
Delhi         True
Bangaluru     True
Lucknow      False
Name: States and Capitals, dtype: bool

In [36]:
s3.isnull().sum()

np.int64(2)

In [37]:
s3.notnull()

Jaipur        True
Mumbai        True
Delhi        False
Bangaluru    False
Lucknow       True
Name: States and Capitals, dtype: bool

In [38]:
s3.notnull().sum()

np.int64(3)

In [39]:
s3['Chandigarh'] = 'Punjab'
s3['Kolkata']    = 'West Bengal'
s3['Gandhi Nagar']= 'Gujrat'
s3

Jaipur              Rajasthan
Mumbai            Maharashtra
Delhi                     NaN
Bangaluru                 NaN
Lucknow         Uttar Pradesh
Chandigarh             Punjab
Kolkata           West Bengal
Gandhi Nagar           Gujrat
Name: States and Capitals, dtype: object

In [40]:
s3.head()

Jaipur           Rajasthan
Mumbai         Maharashtra
Delhi                  NaN
Bangaluru              NaN
Lucknow      Uttar Pradesh
Name: States and Capitals, dtype: object

In [41]:
s3.head(3)

Jaipur      Rajasthan
Mumbai    Maharashtra
Delhi             NaN
Name: States and Capitals, dtype: object

In [42]:
s3.tail()

Bangaluru                 NaN
Lucknow         Uttar Pradesh
Chandigarh             Punjab
Kolkata           West Bengal
Gandhi Nagar           Gujrat
Name: States and Capitals, dtype: object

In [43]:
s3.tail(6)

Delhi                     NaN
Bangaluru                 NaN
Lucknow         Uttar Pradesh
Chandigarh             Punjab
Kolkata           West Bengal
Gandhi Nagar           Gujrat
Name: States and Capitals, dtype: object

In [44]:
s3['abc'] = 'Punjab'
s3

Jaipur              Rajasthan
Mumbai            Maharashtra
Delhi                     NaN
Bangaluru                 NaN
Lucknow         Uttar Pradesh
Chandigarh             Punjab
Kolkata           West Bengal
Gandhi Nagar           Gujrat
abc                    Punjab
Name: States and Capitals, dtype: object

In [45]:
s3.duplicated()

Jaipur          False
Mumbai          False
Delhi           False
Bangaluru        True
Lucknow         False
Chandigarh      False
Kolkata         False
Gandhi Nagar    False
abc              True
Name: States and Capitals, dtype: bool

In [46]:
s3.duplicated().sum()

np.int64(2)

In [47]:
s3.drop_duplicates()

Jaipur              Rajasthan
Mumbai            Maharashtra
Delhi                     NaN
Lucknow         Uttar Pradesh
Chandigarh             Punjab
Kolkata           West Bengal
Gandhi Nagar           Gujrat
Name: States and Capitals, dtype: object

In [48]:
s3.drop_duplicates(inplace= True)

In [49]:
s3

Jaipur              Rajasthan
Mumbai            Maharashtra
Delhi                     NaN
Lucknow         Uttar Pradesh
Chandigarh             Punjab
Kolkata           West Bengal
Gandhi Nagar           Gujrat
Name: States and Capitals, dtype: object

## DATA FRAMES

In [50]:
employee1 = pd.Series({'NAME' : 'ANKUR', 'GENDER' : 'MALE', 'SALARY' : 10000})
employee2 = pd.Series({'NAME' : 'SARWAT', 'GENDER' : 'FEMALE', 'SALARY' : 12890000})
employee3 = pd.Series({'NAME' : 'GEETANJALI', 'GENDER' : 'FEMALE', 'SALARY' : 15670000})
employee4 = pd.Series({'NAME' : 'DISHA', 'GENDER' : 'FEMALE', 'SALARY' : 4500000})
employee5 = pd.Series({'NAME' : 'ARCHIT', 'GENDER' : 'MALE', 'SALARY' : 12500000})
employee6 = pd.Series({'NAME' : 'ANIKET', 'GENDER' : 'MALE', 'SALARY' : 2340000})
employee7 = pd.Series({'NAME' : 'TEJASHRI', 'GENDER' : 'FEMALE', 'SALARY' : 76590000})
employee8 = pd.Series({'NAME' : 'ATHARVA', 'GENDER' : 'MALE', 'SALARY' : 34520000})
employee9 = pd.Series({'NAME' : 'VARAD', 'GENDER' : 'MALE', 'SALARY' : 10007800})
employee10 = pd.Series({'NAME' : 'NISHA', 'GENDER' : 'FEMALE', 'SALARY' : 45630000})
employee11 = pd.Series({'NAME' : 'ATHARV', 'GENDER' : 'MALE', 'SALARY' : 78650000})
employee12 = pd.Series({'NAME' : 'SAHIL', 'GENDER' : 'MALE', 'SALARY' : 56740000})
employee13 = pd.Series({'NAME' : 'UTKARSHA', 'GENDER' : 'FEMALE', 'SALARY' : 567410000})
employee14 = pd.Series({'NAME' : 'MIRAL', 'GENDER' : 'FEMALE', 'SALARY' : 456310000})
employee15 = pd.Series({'NAME' : 'VAISHNAVI', 'GENDER' : 'FEMALE', 'SALARY' : 786540000})

In [51]:
employee = [employee1,employee2,employee3,employee4,employee5,employee6,employee7,employee8,employee9,employee10,employee11,employee12,employee13,employee14,employee15]
df = pd.DataFrame(data = employee,index=range(101,116))
df

           NAME  GENDER     SALARY
101       ANKUR    MALE      10000
102      SARWAT  FEMALE   12890000
103  GEETANJALI  FEMALE   15670000
104       DISHA  FEMALE    4500000
105      ARCHIT    MALE   12500000
106      ANIKET    MALE    2340000
107    TEJASHRI  FEMALE   76590000
108     ATHARVA    MALE   34520000
109       VARAD    MALE   10007800
110       NISHA  FEMALE   45630000
111      ATHARV    MALE   78650000
112       SAHIL    MALE   56740000
113    UTKARSHA  FEMALE  567410000
114       MIRAL  FEMALE  456310000
115   VAISHNAVI  FEMALE  786540000

## IMPORTING CSV FILE

In [53]:
df1 = pd.read_csv('drug200.csv')
df1

FileNotFoundError: [Errno 2] No such file or directory: 'drug200.csv'

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 101 to 115
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   NAME    15 non-null     object
 1   GENDER  15 non-null     object
 2   SALARY  15 non-null     int64
dtypes: int64(1), object(2)
memory usage: 492.0+ bytes

In [55]:
df.head()

           NAME  GENDER    SALARY
101       ANKUR    MALE     10000
102      SARWAT  FEMALE  12890000
103  GEETANJALI  FEMALE  15670000
104       DISHA  FEMALE   4500000
105      ARCHIT    MALE  12500000

In [56]:
df.tail()

          NAME  GENDER     SALARY
111     ATHARV    MALE   78650000
112      SAHIL    MALE   56740000
113   UTKARSHA  FEMALE  567410000
114      MIRAL  FEMALE  456310000
115  VAISHNAVI  FEMALE  786540000

In [57]:
df.name = 'Employee Details'
df.index.name = 'Employee_Id'

In [58]:
df.name

'Employee Details'

In [59]:
df.columns

Index(['NAME', 'GENDER', 'SALARY'], dtype='object')

## ACCESSING DATA FROM DATAFRAME

In [60]:
df

                   NAME  GENDER     SALARY
Employee_Id
101               ANKUR    MALE      10000
102              SARWAT  FEMALE   12890000
103          GEETANJALI  FEMALE   15670000
104               DISHA  FEMALE    4500000
105              ARCHIT    MALE   12500000
106              ANIKET    MALE    2340000
107            TEJASHRI  FEMALE   76590000
108             ATHARVA    MALE   34520000
109               VARAD    MALE   10007800
110               NISHA  FEMALE   45630000
111              ATHARV    MALE   78650000
112               SAHIL    MALE   56740000
113            UTKARSHA  FEMALE  567410000
114               MIRAL  FEMALE  456310000
115           VAISHNAVI  FEMALE  786540000

In [61]:
df['NAME']

Employee_Id
101         ANKUR
102        SARWAT
103    GEETANJALI
104         DISHA
105        ARCHIT
106        ANIKET
107      TEJASHRI
108       ATHARVA
109         VARAD
110         NISHA
111        ATHARV
112         SAHIL
113      UTKARSHA
114         MIRAL
115     VAISHNAVI
Name: NAME, dtype: object

In [62]:
df[['NAME']]

                   NAME
Employee_Id
101               ANKUR
102              SARWAT
103          GEETANJALI
104               DISHA
105              ARCHIT
106              ANIKET
107            TEJASHRI
108             ATHARVA
109               VARAD
110               NISHA
111              ATHARV
112               SAHIL
113            UTKARSHA
114               MIRAL
115           VAISHNAVI

In [63]:
df[['NAME','SALARY']]

                   NAME     SALARY
Employee_Id
101               ANKUR      10000
102              SARWAT   12890000
103          GEETANJALI   15670000
104               DISHA    4500000
105              ARCHIT   12500000
106              ANIKET    2340000
107            TEJASHRI   76590000
108             ATHARVA   34520000
109               VARAD   10007800
110               NISHA   45630000
111              ATHARV   78650000
112               SAHIL   56740000
113            UTKARSHA  567410000
114               MIRAL  456310000
115           VAISHNAVI  786540000

In [64]:
col = ['NAME','SALARY']
df[col]

                   NAME     SALARY
Employee_Id
101               ANKUR      10000
102              SARWAT   12890000
103          GEETANJALI   15670000
104               DISHA    4500000
105              ARCHIT   12500000
106              ANIKET    2340000
107            TEJASHRI   76590000
108             ATHARVA   34520000
109               VARAD   10007800
110               NISHA   45630000
111              ATHARV   78650000
112               SAHIL   56740000
113            UTKARSHA  567410000
114               MIRAL  456310000
115           VAISHNAVI  786540000

In [65]:
df.loc[106]

NAME       ANIKET
GENDER       MALE
SALARY    2340000
Name: 106, dtype: object

In [66]:
df.loc[106]
df.loc[[106]]

               NAME GENDER   SALARY
Employee_Id
106          ANIKET   MALE  2340000

In [67]:
df.iloc[5]

NAME       ANIKET
GENDER       MALE
SALARY    2340000
Name: 106, dtype: object

In [68]:
df.iloc[[5]]

               NAME GENDER   SALARY
Employee_Id
106          ANIKET   MALE  2340000

In [69]:
df.loc[[101,104,105,106,111]]

               NAME  GENDER    SALARY
Employee_Id
101           ANKUR    MALE     10000
104           DISHA  FEMALE   4500000
105          ARCHIT    MALE  12500000
106          ANIKET    MALE   2340000
111          ATHARV    MALE  78650000

## ACCESSING SPECIFIC VALUES

In [70]:
df

                   NAME  GENDER     SALARY
Employee_Id
101               ANKUR    MALE      10000
102              SARWAT  FEMALE   12890000
103          GEETANJALI  FEMALE   15670000
104               DISHA  FEMALE    4500000
105              ARCHIT    MALE   12500000
106              ANIKET    MALE    2340000
107            TEJASHRI  FEMALE   76590000
108             ATHARVA    MALE   34520000
109               VARAD    MALE   10007800
110               NISHA  FEMALE   45630000
111              ATHARV    MALE   78650000
112               SAHIL    MALE   56740000
113            UTKARSHA  FEMALE  567410000
114               MIRAL  FEMALE  456310000
115           VAISHNAVI  FEMALE  786540000

In [71]:
df.loc[108]['NAME']

'ATHARVA'

In [72]:
df.iloc[7]['NAME']

'ATHARVA'

In [73]:
df['NAME'][108]

'ATHARVA'

In [74]:
df['NAME'][7]

KeyError: 7

In [75]:
df.loc[108,'NAME']

'ATHARVA'

In [76]:
df.loc[[102,104,108,112]][['NAME']]

                NAME
Employee_Id
102           SARWAT
104            DISHA
108          ATHARVA
112            SAHIL

In [77]:
df.loc[102::2]

                NAME  GENDER     SALARY
Employee_Id
102           SARWAT  FEMALE   12890000
104            DISHA  FEMALE    4500000
106           ANIKET    MALE    2340000
108          ATHARVA    MALE   34520000
110            NISHA  FEMALE   45630000
112            SAHIL    MALE   56740000
114            MIRAL  FEMALE  456310000

## ADDING AND DELETING ROWS AND COLUMNS

In [78]:
df

                   NAME  GENDER     SALARY
Employee_Id
101               ANKUR    MALE      10000
102              SARWAT  FEMALE   12890000
103          GEETANJALI  FEMALE   15670000
104               DISHA  FEMALE    4500000
105              ARCHIT    MALE   12500000
106              ANIKET    MALE    2340000
107            TEJASHRI  FEMALE   76590000
108             ATHARVA    MALE   34520000
109               VARAD    MALE   10007800
110               NISHA  FEMALE   45630000
111              ATHARV    MALE   78650000
112               SAHIL    MALE   56740000
113            UTKARSHA  FEMALE  567410000
114               MIRAL  FEMALE  456310000
115           VAISHNAVI  FEMALE  786540000

In [79]:
df.loc[116] = ['ETHANS','MALE',100]
df

                   NAME  GENDER     SALARY
Employee_Id
101               ANKUR    MALE      10000
102              SARWAT  FEMALE   12890000
103          GEETANJALI  FEMALE   15670000
104               DISHA  FEMALE    4500000
105              ARCHIT    MALE   12500000
106              ANIKET    MALE    2340000
107            TEJASHRI  FEMALE   76590000
108             ATHARVA    MALE   34520000
109               VARAD    MALE   10007800
110               NISHA  FEMALE   45630000
111              ATHARV    MALE   78650000
112               SAHIL    MALE   56740000
113            UTKARSHA  FEMALE  567410000
114               MIRAL  FEMALE  456310000
115           VAISHNAVI  FEMALE  786540000
116              ETHANS    MALE        100

In [80]:
df['AGE'] = 30
df

                   NAME  GENDER     SALARY  AGE
Employee_Id
101               ANKUR    MALE      10000   30
102              SARWAT  FEMALE   12890000   30
103          GEETANJALI  FEMALE   15670000   30
104               DISHA  FEMALE    4500000   30
105              ARCHIT    MALE   12500000   30
106              ANIKET    MALE    2340000   30
107            TEJASHRI  FEMALE   76590000   30
108             ATHARVA    MALE   34520000   30
109               VARAD    MALE   10007800   30
110               NISHA  FEMALE   45630000   30
111              ATHARV    MALE   78650000   30
112               SAHIL    MALE   56740000   30
113            UTKARSHA  FEMALE  567410000   30
114               MIRAL  FEMALE  456310000   30
115           VAISHNAVI  FEMALE  786540000   30
116              ETHANS    MALE        100   30

In [81]:
df['AGE']= np.random.randint(23,55,16)
df

                   NAME  GENDER     SALARY  AGE
Employee_Id
101               ANKUR    MALE      10000   23
102              SARWAT  FEMALE   12890000   52
103          GEETANJALI  FEMALE   15670000   37
104               DISHA  FEMALE    4500000   40
105              ARCHIT    MALE   12500000   31
106              ANIKET    MALE    2340000   24
107            TEJASHRI  FEMALE   76590000   47
108             ATHARVA    MALE   34520000   29
109               VARAD    MALE   10007800   27
110               NISHA  FEMALE   45630000   33
111              ATHARV    MALE   78650000   24
112               SAHIL    MALE   56740000   35
113            UTKARSHA  FEMALE  567410000   45
114               MIRAL  FEMALE  456310000   51
115           VAISHNAVI  FEMALE  786540000   26
116              ETHANS    MALE        100   33

In [82]:
df['CITY'] = 'PUNE'
df

                   NAME  GENDER     SALARY  AGE  CITY
Employee_Id
101               ANKUR    MALE      10000   23  PUNE
102              SARWAT  FEMALE   12890000   52  PUNE
103          GEETANJALI  FEMALE   15670000   37  PUNE
104               DISHA  FEMALE    4500000   40  PUNE
105              ARCHIT    MALE   12500000   31  PUNE
106              ANIKET    MALE    2340000   24  PUNE
107            TEJASHRI  FEMALE   76590000   47  PUNE
108             ATHARVA    MALE   34520000   29  PUNE
109               VARAD    MALE   10007800   27  PUNE
110               NISHA  FEMALE   45630000   33  PUNE
111              ATHARV    MALE   78650000   24  PUNE
112               SAHIL    MALE   56740000   35  PUNE
113            UTKARSHA  FEMALE  567410000   45  PUNE
114               MIRAL  FEMALE  456310000   51  PUNE
115           VAISHNAVI  FEMALE  786540000   26  PUNE
116              ETHANS    MALE        100   33  PUNE

In [83]:
df.drop('CITY',axis = 1,inplace = True)
df

                   NAME  GENDER     SALARY  AGE
Employee_Id
101               ANKUR    MALE      10000   23
102              SARWAT  FEMALE   12890000   52
103          GEETANJALI  FEMALE   15670000   37
104               DISHA  FEMALE    4500000   40
105              ARCHIT    MALE   12500000   31
106              ANIKET    MALE    2340000   24
107            TEJASHRI  FEMALE   76590000   47
108             ATHARVA    MALE   34520000   29
109               VARAD    MALE   10007800   27
110               NISHA  FEMALE   45630000   33
111              ATHARV    MALE   78650000   24
112               SAHIL    MALE   56740000   35
113            UTKARSHA  FEMALE  567410000   45
114               MIRAL  FEMALE  456310000   51
115           VAISHNAVI  FEMALE  786540000   26
116              ETHANS    MALE        100   33

In [84]:
df.drop(116,axis=0,inplace=True)
df

                   NAME  GENDER     SALARY  AGE
Employee_Id
101               ANKUR    MALE      10000   23
102              SARWAT  FEMALE   12890000   52
103          GEETANJALI  FEMALE   15670000   37
104               DISHA  FEMALE    4500000   40
105              ARCHIT    MALE   12500000   31
106              ANIKET    MALE    2340000   24
107            TEJASHRI  FEMALE   76590000   47
108             ATHARVA    MALE   34520000   29
109               VARAD    MALE   10007800   27
110               NISHA  FEMALE   45630000   33
111              ATHARV    MALE   78650000   24
112               SAHIL    MALE   56740000   35
113            UTKARSHA  FEMALE  567410000   45
114               MIRAL  FEMALE  456310000   51
115           VAISHNAVI  FEMALE  786540000   26

In [85]:
name = input('Enter your name :')
gender = input('Enter your gender :')
salary = int(input('Enter your salary :'))
age = int(input('Enter your age :'))

df.loc[116] = [name,gender,salary,age]
df

Enter your name : RAKHI
Enter your gender : FEMALE
Enter your salary : 50000
Enter your age : 23

                   NAME  GENDER     SALARY  AGE
Employee_Id
101               ANKUR    MALE      10000   23
102              SARWAT  FEMALE   12890000   52
103          GEETANJALI  FEMALE   15670000   37
104               DISHA  FEMALE    4500000   40
105              ARCHIT    MALE   12500000   31
106              ANIKET    MALE    2340000   24
107            TEJASHRI  FEMALE   76590000   47
108             ATHARVA    MALE   34520000   29
109               VARAD    MALE   10007800   27
110               NISHA  FEMALE   45630000   33
111              ATHARV    MALE   78650000   24
112               SAHIL    MALE   56740000   35
113            UTKARSHA  FEMALE  567410000   45
114               MIRAL  FEMALE  456310000   51
115           VAISHNAVI  FEMALE  786540000   26
116               RAKHI  FEMALE      50000   23

In [86]:
df.loc[116,'SALARY'] = 100
df

                   NAME  GENDER     SALARY  AGE
Employee_Id
101               ANKUR    MALE      10000   23
102              SARWAT  FEMALE   12890000   52
103          GEETANJALI  FEMALE   15670000   37
104               DISHA  FEMALE    4500000   40
105              ARCHIT    MALE   12500000   31
106              ANIKET    MALE    2340000   24
107            TEJASHRI  FEMALE   76590000   47
108             ATHARVA    MALE   34520000   29
109               VARAD    MALE   10007800   27
110               NISHA  FEMALE   45630000   33
111              ATHARV    MALE   78650000   24
112               SAHIL    MALE   56740000   35
113            UTKARSHA  FEMALE  567410000   45
114               MIRAL  FEMALE  456310000   51
115           VAISHNAVI  FEMALE  786540000   26
116               RAKHI  FEMALE        100   23

## ACCESSING DATA BASED ON CONDITIONS

In [87]:
df

                   NAME  GENDER     SALARY  AGE
Employee_Id
101               ANKUR    MALE      10000   23
102              SARWAT  FEMALE   12890000   52
103          GEETANJALI  FEMALE   15670000   37
104               DISHA  FEMALE    4500000   40
105              ARCHIT    MALE   12500000   31
106              ANIKET    MALE    2340000   24
107            TEJASHRI  FEMALE   76590000   47
108             ATHARVA    MALE   34520000   29
109               VARAD    MALE   10007800   27
110               NISHA  FEMALE   45630000   33
111              ATHARV    MALE   78650000   24
112               SAHIL    MALE   56740000   35
113            UTKARSHA  FEMALE  567410000   45
114               MIRAL  FEMALE  456310000   51
115           VAISHNAVI  FEMALE  786540000   26
116               RAKHI  FEMALE        100   23

In [88]:
df[df.AGE>40]

                 NAME  GENDER     SALARY  AGE
Employee_Id
102            SARWAT  FEMALE   12890000   52
107          TEJASHRI  FEMALE   76590000   47
113          UTKARSHA  FEMALE  567410000   45
114             MIRAL  FEMALE  456310000   51

In [89]:
df[df.AGE>40][['NAME','SALARY']]

                 NAME     SALARY
Employee_Id
102            SARWAT   12890000
107          TEJASHRI   76590000
113          UTKARSHA  567410000
114             MIRAL  456310000

In [90]:
df[df.NAME=='ANKUR']

              NAME GENDER  SALARY  AGE
Employee_Id
101          ANKUR   MALE   10000   23

In [91]:
df[df.GENDER=='MALE']

                NAME GENDER    SALARY  AGE
Employee_Id
101            ANKUR   MALE     10000   23
105           ARCHIT   MALE  12500000   31
106           ANIKET   MALE   2340000   24
108          ATHARVA   MALE  34520000   29
109            VARAD   MALE  10007800   27
111           ATHARV   MALE  78650000   24
112            SAHIL   MALE  56740000   35

In [92]:
df[df.GENDER=='MALE'][df.SALARY>10000000]

C:\Users\roder\AppData\Local\Temp\ipykernel_15632\4230783272.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df[df.GENDER=='MALE'][df.SALARY>10000000]

                NAME GENDER    SALARY  AGE
Employee_Id
105           ARCHIT   MALE  12500000   31
108          ATHARVA   MALE  34520000   29
109            VARAD   MALE  10007800   27
111           ATHARV   MALE  78650000   24
112            SAHIL   MALE  56740000   35

In [93]:
df[df.GENDER=='MALE'][df.SALARY>10000000][df.AGE>32]

C:\Users\roder\AppData\Local\Temp\ipykernel_15632\359524044.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df[df.GENDER=='MALE'][df.SALARY>10000000][df.AGE>32]
C:\Users\roder\AppData\Local\Temp\ipykernel_15632\359524044.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df[df.GENDER=='MALE'][df.SALARY>10000000][df.AGE>32]

              NAME GENDER    SALARY  AGE
Employee_Id
112          SAHIL   MALE  56740000   35

## IMPORTANT FUNCTIONS

In [94]:
df

                   NAME  GENDER     SALARY  AGE
Employee_Id
101               ANKUR    MALE      10000   23
102              SARWAT  FEMALE   12890000   52
103          GEETANJALI  FEMALE   15670000   37
104               DISHA  FEMALE    4500000   40
105              ARCHIT    MALE   12500000   31
106              ANIKET    MALE    2340000   24
107            TEJASHRI  FEMALE   76590000   47
108             ATHARVA    MALE   34520000   29
109               VARAD    MALE   10007800   27
110               NISHA  FEMALE   45630000   33
111              ATHARV    MALE   78650000   24
112               SAHIL    MALE   56740000   35
113            UTKARSHA  FEMALE  567410000   45
114               MIRAL  FEMALE  456310000   51
115           VAISHNAVI  FEMALE  786540000   26
116               RAKHI  FEMALE        100   23

In [95]:
df.loc[117] = df.loc[111]
df.loc[118] = df.loc[114]

df.loc[119] = ['Ankush','Male',np.nan,45]
df.loc[120] = ['Krishna','Male',np.nan,45]

df

                   NAME  GENDER       SALARY  AGE
Employee_Id
101               ANKUR    MALE      10000.0   23
102              SARWAT  FEMALE   12890000.0   52
103          GEETANJALI  FEMALE   15670000.0   37
104               DISHA  FEMALE    4500000.0   40
105              ARCHIT    MALE   12500000.0   31
106              ANIKET    MALE    2340000.0   24
107            TEJASHRI  FEMALE   76590000.0   47
108             ATHARVA    MALE   34520000.0   29
109               VARAD    MALE   10007800.0   27
110               NISHA  FEMALE   45630000.0   33
111              ATHARV    MALE   78650000.0   24
112               SAHIL    MALE   56740000.0   35
113            UTKARSHA  FEMALE  567410000.0   45
114               MIRAL  FEMALE  456310000.0   51
115           VAISHNAVI  FEMALE  786540000.0   26
116               RAKHI  FEMALE        100.0   23
117              ATHARV    MALE   78650000.0   24
118               MIRAL  FEMALE  456310000.0   51
119              Ankush    Male          NaN   45
120             Krishna    Male          NaN   45

In [96]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20 entries, 101 to 120
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   NAME    20 non-null     object
 1   GENDER  20 non-null     object
 2   SALARY  18 non-null     float64
 3   AGE     20 non-null     int64
dtypes: float64(1), int64(1), object(2)
memory usage: 800.0+ bytes

In [97]:
df.head()

                   NAME  GENDER      SALARY  AGE
Employee_Id
101               ANKUR    MALE     10000.0   23
102              SARWAT  FEMALE  12890000.0   52
103          GEETANJALI  FEMALE  15670000.0   37
104               DISHA  FEMALE   4500000.0   40
105              ARCHIT    MALE  12500000.0   31

In [98]:
df.tail()

                NAME  GENDER       SALARY  AGE
Employee_Id
116            RAKHI  FEMALE        100.0   23
117           ATHARV    MALE   78650000.0   24
118            MIRAL  FEMALE  456310000.0   51
119           Ankush    Male          NaN   45
120          Krishna    Male          NaN   45

In [99]:
df.isnull().sum()

NAME      0
GENDER    0
SALARY    2
AGE       0
dtype: int64

In [100]:
df.notnull().sum()

NAME      20
GENDER    20
SALARY    18
AGE       20
dtype: int64

In [101]:
df.duplicated().sum()

np.int64(2)

In [102]:
df.nunique()

NAME      18
GENDER     3
SALARY    16
AGE       14
dtype: int64

In [103]:
df.NAME.unique()

array(['ANKUR', 'SARWAT', 'GEETANJALI', 'DISHA', 'ARCHIT', 'ANIKET',
       'TEJASHRI', 'ATHARVA', 'VARAD', 'NISHA', 'ATHARV', 'SAHIL',
       'UTKARSHA', 'MIRAL', 'VAISHNAVI', 'RAKHI', 'Ankush', 'Krishna'],
      dtype=object)

In [104]:
df.GENDER.unique()

array(['MALE', 'FEMALE', 'Male'], dtype=object)

In [105]:
df.sort_values(by = 'NAME')

                   NAME  GENDER       SALARY  AGE
Employee_Id
106              ANIKET    MALE    2340000.0   24
101               ANKUR    MALE      10000.0   23
105              ARCHIT    MALE   12500000.0   31
117              ATHARV    MALE   78650000.0   24
111              ATHARV    MALE   78650000.0   24
108             ATHARVA    MALE   34520000.0   29
119              Ankush    Male          NaN   45
104               DISHA  FEMALE    4500000.0   40
103          GEETANJALI  FEMALE   15670000.0   37
120             Krishna    Male          NaN   45
114               MIRAL  FEMALE  456310000.0   51
118               MIRAL  FEMALE  456310000.0   51
110               NISHA  FEMALE   45630000.0   33
116               RAKHI  FEMALE        100.0   23
112               SAHIL    MALE   56740000.0   35
102              SARWAT  FEMALE   12890000.0   52
107            TEJASHRI  FEMALE   76590000.0   47
113            UTKARSHA  FEMALE  567410000.0   45
115           VAISHNAVI  FEMALE  786540000.0   26
109               VARAD    MALE   10007800.0   27

In [106]:
df.sort_values(by = 'NAME',ascending= False)

                   NAME  GENDER       SALARY  AGE
Employee_Id
109               VARAD    MALE   10007800.0   27
115           VAISHNAVI  FEMALE  786540000.0   26
113            UTKARSHA  FEMALE  567410000.0   45
107            TEJASHRI  FEMALE   76590000.0   47
102              SARWAT  FEMALE   12890000.0   52
112               SAHIL    MALE   56740000.0   35
116               RAKHI  FEMALE        100.0   23
110               NISHA  FEMALE   45630000.0   33
118               MIRAL  FEMALE  456310000.0   51
114               MIRAL  FEMALE  456310000.0   51
120             Krishna    Male          NaN   45
103          GEETANJALI  FEMALE   15670000.0   37
104               DISHA  FEMALE    4500000.0   40
119              Ankush    Male          NaN   45
108             ATHARVA    MALE   34520000.0   29
117              ATHARV    MALE   78650000.0   24
111              ATHARV    MALE   78650000.0   24
105              ARCHIT    MALE   12500000.0   31
101               ANKUR    MALE      10000.0   23
106              ANIKET    MALE    2340000.0   24

In [107]:
pd.concat([df,df],axis=1)

,NAME,GENDER,SALARY,AGE,NAME,GENDER,SALARY,AGE
Employee_Id,,,,,,,,
101,ANKUR,MALE,10000.0,23,ANKUR,MALE,10000.0,23
102,SARWAT,FEMALE,12890000.0,52,SARWAT,FEMALE,12890000.0,52
103,GEETANJALI,FEMALE,15670000.0,37,GEETANJALI,FEMALE,15670000.0,37
104,DISHA,FEMALE,4500000.0,40,DISHA,FEMALE,4500000.0,40
105,ARCHIT,MALE,12500000.0,31,ARCHIT,MALE,12500000.0,31
106,ANIKET,MALE,2340000.0,24,ANIKET,MALE,2340000.0,24
107,TEJASHRI,FEMALE,76590000.0,47,TEJASHRI,FEMALE,76590000.0,47
108,ATHARVA,MALE,34520000.0,29,ATHARVA,MALE,34520000.0,29
109,VARAD,MALE,10007800.0,27,VARAD,MALE,10007800.0,27
110,NISHA,FEMALE,45630000.0,33,NISHA,FEMALE,45630000.0,33
111,ATHARV,MALE,78650000.0,24,ATHARV,MALE,78650000.0,24
112,SAHIL,MALE,56740000.0,35,SAHIL,MALE,56740000.0,35
113,UTKARSHA,FEMALE,567410000.0,45,UTKARSHA,FEMALE,567410000.0,45
114,MIRAL,FEMALE,456310000.0,51,MIRAL,FEMALE,456310000.0,51
115,VAISHNAVI,FEMALE,786540000.0,26,VAISHNAVI,FEMALE,786540000.0,26
116,RAKHI,FEMALE,100.0,23,RAKHI,FEMALE,100.0,23
117,ATHARV,MALE,78650000.0,24,ATHARV,MALE,78650000.0,24
118,MIRAL,FEMALE,456310000.0,51,MIRAL,FEMALE,456310000.0,51
119,Ankush,Male,NaN,45,Ankush,Male,NaN,45
120,Krishna,Male,NaN,45,Krishna,Male,NaN,45

In [108]:
pd.concat([df,df],axis=0)

                   NAME  GENDER       SALARY  AGE
Employee_Id
101               ANKUR    MALE      10000.0   23
102              SARWAT  FEMALE   12890000.0   52
103          GEETANJALI  FEMALE   15670000.0   37
104               DISHA  FEMALE    4500000.0   40
105              ARCHIT    MALE   12500000.0   31
106              ANIKET    MALE    2340000.0   24
107            TEJASHRI  FEMALE   76590000.0   47
108             ATHARVA    MALE   34520000.0   29
109               VARAD    MALE   10007800.0   27
110               NISHA  FEMALE   45630000.0   33
111              ATHARV    MALE   78650000.0   24
112               SAHIL    MALE   56740000.0   35
113            UTKARSHA  FEMALE  567410000.0   45
114               MIRAL  FEMALE  456310000.0   51
115           VAISHNAVI  FEMALE  786540000.0   26
116               RAKHI  FEMALE        100.0   23
117              ATHARV    MALE   78650000.0   24
118               MIRAL  FEMALE  456310000.0   51
119              Ankush    Male          NaN   45
120             Krishna    Male          NaN   45
101               ANKUR    MALE      10000.0   23
102              SARWAT  FEMALE   12890000.0   52
103          GEETANJALI  FEMALE   15670000.0   37
104               DISHA  FEMALE    4500000.0   40
105              ARCHIT    MALE   12500000.0   31
106              ANIKET    MALE    2340000.0   24
107            TEJASHRI  FEMALE   76590000.0   47
108             ATHARVA    MALE   34520000.0   29
109               VARAD    MALE   10007800.0   27
110               NISHA  FEMALE   45630000.0   33
111              ATHARV    MALE   78650000.0   24
112               SAHIL    MALE   56740000.0   35
113            UTKARSHA  FEMALE  567410000.0   45
114               MIRAL  FEMALE  456310000.0   51
115           VAISHNAVI  FEMALE  786540000.0   26
116               RAKHI  FEMALE        100.0   23
117              ATHARV    MALE   78650000.0   24
118               MIRAL  FEMALE  456310000.0   51
119              Ankush    Male          NaN   45
120             Krishna    Male          NaN   45

In [109]:
df.GENDER.value_counts()

GENDER
FEMALE    10
MALE       8
Male       2
Name: count, dtype: int64

In [110]:
df.count()

NAME      20
GENDER    20
SALARY    18
AGE       20
dtype: int64

In [111]:
df.describe()

             SALARY        AGE
count  1.800000e+01  20.000000
mean   1.497371e+08  35.600000
std    2.399608e+08  10.560104
min    1.000000e+02  23.000000
25%    1.063085e+07  25.500000
50%    4.007500e+07  34.000000
75%    7.865000e+07  45.000000
max    7.865400e+08  52.000000

In [112]:
df.AGE.mean()

np.float64(35.6)

In [113]:
df

                   NAME  GENDER       SALARY  AGE
Employee_Id
101               ANKUR    MALE      10000.0   23
102              SARWAT  FEMALE   12890000.0   52
103          GEETANJALI  FEMALE   15670000.0   37
104               DISHA  FEMALE    4500000.0   40
105              ARCHIT    MALE   12500000.0   31
106              ANIKET    MALE    2340000.0   24
107            TEJASHRI  FEMALE   76590000.0   47
108             ATHARVA    MALE   34520000.0   29
109               VARAD    MALE   10007800.0   27
110               NISHA  FEMALE   45630000.0   33
111              ATHARV    MALE   78650000.0   24
112               SAHIL    MALE   56740000.0   35
113            UTKARSHA  FEMALE  567410000.0   45
114               MIRAL  FEMALE  456310000.0   51
115           VAISHNAVI  FEMALE  786540000.0   26
116               RAKHI  FEMALE        100.0   23
117              ATHARV    MALE   78650000.0   24
118               MIRAL  FEMALE  456310000.0   51
119              Ankush    Male          NaN   45
120             Krishna    Male          NaN   45

In [114]:
df.SALARY.mean()

np.float64(149737105.55555555)

In [115]:
df.groupby(by='GENDER')['AGE'].mean()

GENDER
FEMALE    40.500
MALE      27.125
Male      45.000
Name: AGE, dtype: float64

In [116]:
df.groupby(by='GENDER')['SALARY'].mean()

GENDER
FEMALE    242185010.0
MALE       34177225.0
Male              NaN
Name: SALARY, dtype: float64

In [117]:
df['CITY'] = ['PUNE','MUMBAI','NAGPUR','DELHI','PUNE','MUMBAI','NAGPUR','DELHI','PUNE','MUMBAI','NAGPUR','DELHI','PUNE','MUMBAI','NAGPUR','DELHI','PUNE','MUMBAI','NAGPUR','DELHI']
df

                   NAME  GENDER       SALARY  AGE    CITY
Employee_Id
101               ANKUR    MALE      10000.0   23    PUNE
102              SARWAT  FEMALE   12890000.0   52  MUMBAI
103          GEETANJALI  FEMALE   15670000.0   37  NAGPUR
104               DISHA  FEMALE    4500000.0   40   DELHI
105              ARCHIT    MALE   12500000.0   31    PUNE
106              ANIKET    MALE    2340000.0   24  MUMBAI
107            TEJASHRI  FEMALE   76590000.0   47  NAGPUR
108             ATHARVA    MALE   34520000.0   29   DELHI
109               VARAD    MALE   10007800.0   27    PUNE
110               NISHA  FEMALE   45630000.0   33  MUMBAI
111              ATHARV    MALE   78650000.0   24  NAGPUR
112               SAHIL    MALE   56740000.0   35   DELHI
113            UTKARSHA  FEMALE  567410000.0   45    PUNE
114               MIRAL  FEMALE  456310000.0   51  MUMBAI
115           VAISHNAVI  FEMALE  786540000.0   26  NAGPUR
116               RAKHI  FEMALE        100.0   23   DELHI
117              ATHARV    MALE   78650000.0   24    PUNE
118               MIRAL  FEMALE  456310000.0   51  MUMBAI
119              Ankush    Male          NaN   45  NAGPUR
120             Krishna    Male          NaN   45   DELHI

In [118]:
df.groupby(by=['CITY','GENDER'])['SALARY'].mean()

CITY    GENDER
DELHI   FEMALE    2.250050e+06
        MALE      4.563000e+07
        Male               NaN
MUMBAI  FEMALE    2.427850e+08
        MALE      2.340000e+06
NAGPUR  FEMALE    2.929333e+08
        MALE      7.865000e+07
        Male               NaN
PUNE    FEMALE    5.674100e+08
        MALE      2.529195e+07
Name: SALARY, dtype: float64

In [119]:
df.duplicated().sum()

np.int64(1)

In [120]:
df.drop_duplicates(inplace=True)

In [121]:
df.duplicated().sum()

np.int64(0)

In [122]:
df.SALARY.mean()

np.float64(131703405.88235295)

In [123]:
df.SALARY.replace(np.nan,df.SALARY.mean())

Employee_Id
101    1.000000e+04
102    1.289000e+07
103    1.567000e+07
104    4.500000e+06
105    1.250000e+07
106    2.340000e+06
107    7.659000e+07
108    3.452000e+07
109    1.000780e+07
110    4.563000e+07
111    7.865000e+07
112    5.674000e+07
113    5.674100e+08
114    4.563100e+08
115    7.865400e+08
116    1.000000e+02
117    7.865000e+07
119    1.317034e+08
120    1.317034e+08
Name: SALARY, dtype: float64

In [124]:
df

                   NAME  GENDER       SALARY  AGE    CITY
Employee_Id
101               ANKUR    MALE      10000.0   23    PUNE
102              SARWAT  FEMALE   12890000.0   52  MUMBAI
103          GEETANJALI  FEMALE   15670000.0   37  NAGPUR
104               DISHA  FEMALE    4500000.0   40   DELHI
105              ARCHIT    MALE   12500000.0   31    PUNE
106              ANIKET    MALE    2340000.0   24  MUMBAI
107            TEJASHRI  FEMALE   76590000.0   47  NAGPUR
108             ATHARVA    MALE   34520000.0   29   DELHI
109               VARAD    MALE   10007800.0   27    PUNE
110               NISHA  FEMALE   45630000.0   33  MUMBAI
111              ATHARV    MALE   78650000.0   24  NAGPUR
112               SAHIL    MALE   56740000.0   35   DELHI
113            UTKARSHA  FEMALE  567410000.0   45    PUNE
114               MIRAL  FEMALE  456310000.0   51  MUMBAI
115           VAISHNAVI  FEMALE  786540000.0   26  NAGPUR
116               RAKHI  FEMALE        100.0   23   DELHI
117              ATHARV    MALE   78650000.0   24    PUNE
119              Ankush    Male          NaN   45  NAGPUR
120             Krishna    Male          NaN   45   DELHI

In [125]:
df.SALARY.replace(np.nan,df.SALARY.mean(),inplace = True)
df

C:\Users\roder\AppData\Local\Temp\ipykernel_15632\1203343733.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.SALARY.replace(np.nan,df.SALARY.mean(),inplace = True)

                   NAME  GENDER        SALARY  AGE    CITY
Employee_Id
101               ANKUR    MALE  1.000000e+04   23    PUNE
102              SARWAT  FEMALE  1.289000e+07   52  MUMBAI
103          GEETANJALI  FEMALE  1.567000e+07   37  NAGPUR
104               DISHA  FEMALE  4.500000e+06   40   DELHI
105              ARCHIT    MALE  1.250000e+07   31    PUNE
106              ANIKET    MALE  2.340000e+06   24  MUMBAI
107            TEJASHRI  FEMALE  7.659000e+07   47  NAGPUR
108             ATHARVA    MALE  3.452000e+07   29   DELHI
109               VARAD    MALE  1.000780e+07   27    PUNE
110               NISHA  FEMALE  4.563000e+07   33  MUMBAI
111              ATHARV    MALE  7.865000e+07   24  NAGPUR
112               SAHIL    MALE  5.674000e+07   35   DELHI
113            UTKARSHA  FEMALE  5.674100e+08   45    PUNE
114               MIRAL  FEMALE  4.563100e+08   51  MUMBAI
115           VAISHNAVI  FEMALE  7.865400e+08   26  NAGPUR
116               RAKHI  FEMALE  1.000000e+02   23   DELHI
117              ATHARV    MALE  7.865000e+07   24    PUNE
119              Ankush    Male  1.317034e+08   45  NAGPUR
120             Krishna    Male  1.317034e+08   45   DELHI